version: "1.0"
docsets:
  - id: mcp-typescript-sdk
    name: MCP TypeScript SDK
    description: Official TypeScript SDK for Model Context Protocol
    sources:
      - url: https://github.com/modelcontextprotocol/typescript-sdk.git
        type: git_repo
        paths:
          - README.md
          - CONTRIBUTING.md
          - src/examples/
        branch: main
  - id: vitepress-docs
    name: VitePress Documentation
    description: VitePress static site generator documentation
    sources:
      - url: https://github.com/vuejs/vitepress.git
        type: git_repo
        branch: main
        paths:
          - README.md
          - docs/en
          - template/
  - id: pipeship-full
    name: pipeship-full-docs
    description: >-
      Zip archive:
      https://bahnhub.tech.rz.db.de/artifactory/pipeship-generic-stage-dev-local/docs-as-code/latest/pipeship-docs.tar.gz
    sources:
      - type: zip
        url: >-
          https://bahnhub.tech.rz.db.de/artifactory/pipeship-generic-stage-dev-local/docs-as-code/latest/pipeship-docs.tar.gz
